sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t bengroever/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bengroever/docker-react npm run test